CREATE TABLE [USysConnect] (
  [ID] AUTOINCREMENT CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [Drvr] VARCHAR (50),
  [ServerAddress] VARCHAR (50),
  [DatabaseName] VARCHAR (50),
  [AppName] VARCHAR (50),
  [UID] VARCHAR (100),
  [PWD] VARCHAR (100)
)
