dbMemo "SQL" ="SELECT IIf(p.StatusID In (1,2,3),0,1) AS StatusGroup, IIf(p.StatusID In (1,2,3),"
    "'Open Projects','Closed Projects') AS StatusGroupLabel, p.ProjectID, p.ProjectNa"
    "me, p.ProjectDescription, p.Notes AS ProjectNotes, pa.ProjectAreaName, ps.Status"
    "Name AS ProjectStatus, p.StartDate AS ProjectStartDate, p.CompletionDate AS Proj"
    "ectCompletionDate, s.StepID, s.StepName, st.StepTypeName, ss.StatusName AS StepS"
    "tatus, s.StartDate AS StepStartDate, s.CompletionDate AS StepCompletionDate, Cou"
    "nt(ses.SessionID) AS SessionCount, Nz(Sum(ses.RevisionCycles),0) AS RevisionTota"
    "l, Nz(Sum(IIf(ses.ContextReset,1,0)),0) AS ResetCount\015\012FROM (((((tblProjec"
    "t AS p LEFT JOIN tlkpProjectArea AS pa ON p.ProjectAreaID = pa.ProjectAreaID) LE"
    "FT JOIN tlkpStatus AS ps ON p.StatusID = ps.StatusID) LEFT JOIN tblStep AS s ON "
    "p.ProjectID = s.ProjectID) LEFT JOIN tlkpStepType AS st ON s.StepTypeID = st.Ste"
    "pTypeID) LEFT JOIN tlkpStatus AS ss ON s.StatusID = ss.StatusID) LEFT JOIN tblSe"
    "ssion AS ses ON s.StepID = ses.StepID\015\012GROUP BY IIf(p.StatusID In (1,2,3),"
    "0,1), IIf(p.StatusID In (1,2,3),'Open Projects','Closed Projects'), p.ProjectID,"
    " p.ProjectName, p.ProjectDescription, p.Notes, pa.ProjectAreaName, ps.StatusName"
    ", p.StartDate, p.CompletionDate, s.StepID, s.StepName, st.StepTypeName, ss.Statu"
    "sName, s.StartDate, s.CompletionDate;\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
Begin
End
